name: moreComplex
version: 1.0.0
author: bc2098
description: test configuration, more complex

packets:
  SysComplexPacket:
    version: 1.0.0

  TestBasePacket:
    version: 1.0.0

  TestMyPacket:
    version: 1.0.0

  RtPacket
    version: 1.0.0
    
rights:
  simple:
    version: 1.0.0

spaceApp: SysComplexPacket.CplxSpaceApp
userData: SysComplexPacket.CplxUserData

# postInstallScript:
  # source:
  # transport: