name: simple
version: 1.0.1
author: bc2098
description: test configuration

packets:
  SysPacket:
    version: 1.0.0

  TestBasePacket:
    version: 1.0.0

  TestMyPacket:
    version: 1.0.0

rights:
  simple:
    version: 1.0.0

spaceApp: SysPacket.TestSpaceApp
userData: SysPacket.TestUserData

# postInstallScript:
  # source:
  # transport: